apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: app
spec:
  sessionAffinity: None
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
